name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install package in development mode for proper imports
        pip install -e .

    - name: Run pre-commit hooks (code quality and linting)
      run: |
        # Pre-commit handles all code quality checks with consistent versions
        pre-commit run --all-files

    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short

    - name: Run project setup tests
      run: |
        python tests/test_project_setup.py
